
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <SessionContextWrapper>
      <html lang="en">
        <body
          className={`${youtubeSans.variable} antialiased`}
        >
         <div className="flex justify-center bg-border">
           <div className="flex flex-col w-full max-w-[80rem] bg-background">
            <Header />
            {children}
          </div>
         </div>
        </body>
      </html>
    </SessionContextWrapper>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const youtubeSans = localFont({
  src: [
    {
      path: "../public/fonts/YTSans-Light-v1-1.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/YTSans-Medium-v1-1.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/YTSans-Bold-v1-1.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-youtube-sans",
  display: "swap",
});

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header"; import SessionContextWrapper from "./SessionContext";

